#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

# boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  polybar -m | sed s/:.*// | tac | while read -r monitor; do
    monitor=$monitor polybar -c "$SCRIPTPATH/polybar.config" mainbar &> /dev/null &
  done
fi
