" Generated by vim-plug
" Fri Nov 20 14:49:36 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '48fe0dd4f629bb1282277ba8a6757a84c13a4dda'
silent! let g:plugs['completion-nvim'].commit = '8c028d007ca314d7734d83dcc05db1ed103db9b5'
silent! let g:plugs['fzf'].commit = '7acdaf0b4335a6c089bce5b73ff23aeb3b9d9c92'
silent! let g:plugs['fzf.vim'].commit = '53b3aea0da5e3581e224c958dbc13558cbe5daee'
silent! let g:plugs['gruvbox-material'].commit = '188b2ffc9a24cfd5dd0abea4e8e85258eaee9712'
silent! let g:plugs['lightline.vim'].commit = '543ee323a4a63fd32cc17dc57edea9c00962bb12'
silent! let g:plugs['lsp_extensions.nvim'].commit = '2ea512d873725a50136c49acc82deab1ee71ad49'
silent! let g:plugs['nerdtree'].commit = '14af89743ac1c31ff9bb43682025eda50333a7d5'
silent! let g:plugs['nvim-lspconfig'].commit = '4f19567fb76438d39ed196ae5b4e06b749e75e16'
silent! let g:plugs['nvim-treesitter'].commit = '289cdc9da8f7f21dcbf814032e9277ef0e9790a0'
silent! let g:plugs['tmuxline.vim'].commit = '7001ab359f2bc699b7000c297a0d9e9a897b70cf'
silent! let g:plugs['ultisnips'].commit = 'b837416c1ffe39b168baee35c0938739e96211c5'
silent! let g:plugs['vim-gitgutter'].commit = '987a33355ef424161fdbc4e5d625b5b5aed9704c'
silent! let g:plugs['vim-grepper'].commit = 'e9004ce564891412cfe433cfbb97295cccd06b39'
silent! let g:plugs['vim-polyglot'].commit = 'c228e993ad6a8b79db5a5a77aecfdbd8e92ea31f'
silent! let g:plugs['vim-snippets'].commit = 'e438b06d59115d4b491f7aa73d3140af44f86175'
silent! let g:plugs['vim-visual-multi'].commit = '3b9c8c630daba920741f1fbf6696b7d32d020660'
silent! let g:plugs['vista.vim'].commit = 'bc3b2a74efb253be4b79cc7b70b192e1360f26c1'
silent! let g:plugs['zoomwintab.vim'].commit = '3b33368ed2ff6138d07f7ee148306cce7d7f6b7c'

PlugUpdate!

