" Generated by vim-plug
" Fri Nov 13 10:01:32 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '1ec573bf0df6cbc5eef8b593f93081e4c1837c1b'
silent! let g:plugs['completion-nvim'].commit = '3b6774ed1c1b4720efe3385f06883483f5e16884'
silent! let g:plugs['diagnostic-nvim'].commit = 'bef1c6140563cb6416081b2517ae9953cd4e05ab'
silent! let g:plugs['fzf'].commit = '75b8cca3b3d0663ea4102f08c763cf2b0b999f88'
silent! let g:plugs['fzf.vim'].commit = '53b3aea0da5e3581e224c958dbc13558cbe5daee'
silent! let g:plugs['lightline.vim'].commit = '2d482e82f2e13c6d7bad3a0aabfc44f8aba945ed'
silent! let g:plugs['lsp_extensions.nvim'].commit = '2ea512d873725a50136c49acc82deab1ee71ad49'
silent! let g:plugs['nerdtree'].commit = '14af89743ac1c31ff9bb43682025eda50333a7d5'
silent! let g:plugs['nvim-lspconfig'].commit = '60133c47e0fd82556d7ca092546ebfa8d047466e'
silent! let g:plugs['tmuxline.vim'].commit = '7001ab359f2bc699b7000c297a0d9e9a897b70cf'
silent! let g:plugs['ultisnips'].commit = 'b837416c1ffe39b168baee35c0938739e96211c5'
silent! let g:plugs['vim-gitgutter'].commit = '987a33355ef424161fdbc4e5d625b5b5aed9704c'
silent! let g:plugs['vim-grepper'].commit = 'e9004ce564891412cfe433cfbb97295cccd06b39'
silent! let g:plugs['vim-one'].commit = 'f8bcef1968f01842d92abbcb098ec28ad3931ea5'
silent! let g:plugs['vim-polyglot'].commit = '4af1321588c7dcb718022226cb27ec325973c2f0'
silent! let g:plugs['vim-snippets'].commit = '0f3d4d187c842419fe6e131fe20f5f3336418a62'
silent! let g:plugs['vim-startify'].commit = 'f2fc11844b234479d37bef37faa7ceb2aade788b'
silent! let g:plugs['vim-visual-multi'].commit = '812ca5cff230cc0a21cce6b9d71db3868a6d6f85'
silent! let g:plugs['vista.vim'].commit = 'bc3b2a74efb253be4b79cc7b70b192e1360f26c1'
silent! let g:plugs['zoomwintab.vim'].commit = '3b33368ed2ff6138d07f7ee148306cce7d7f6b7c'

PlugUpdate!

