" Generated by vim-plug
" Fri Oct 23 15:27:36 2020
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '557a1ed5da70cb443a8650766f4e8ea95e8c0da3'
silent! let g:plugs['completion-nvim'].commit = '3b6774ed1c1b4720efe3385f06883483f5e16884'
silent! let g:plugs['diagnostic-nvim'].commit = 'bef1c6140563cb6416081b2517ae9953cd4e05ab'
silent! let g:plugs['fzf'].commit = 'd2d4d68585ee6b4f4e92d9ead65937168f5984b8'
silent! let g:plugs['fzf.vim'].commit = 'ddc377c0d3b886f2046b70d087a4dd89c903fdc2'
silent! let g:plugs['lsp_extensions.nvim'].commit = '2ea512d873725a50136c49acc82deab1ee71ad49'
silent! let g:plugs['nerdtree'].commit = '14af89743ac1c31ff9bb43682025eda50333a7d5'
silent! let g:plugs['nvim-lspconfig'].commit = '60133c47e0fd82556d7ca092546ebfa8d047466e'
silent! let g:plugs['tmuxline.vim'].commit = '7001ab359f2bc699b7000c297a0d9e9a897b70cf'
silent! let g:plugs['ultisnips'].commit = 'e6478871c04bb75f3c6cb9b90e171fffbf9c8ff3'
silent! let g:plugs['vim-airline'].commit = '8608270bd39e9aa31bbdb8cd22b2ba776037feb6'
silent! let g:plugs['vim-airline-themes'].commit = 'e1b0d9f86cf89e84b15c459683fd72730e51a054'
silent! let g:plugs['vim-fugitive'].commit = '89e6b5e4e1d8152bfc3c26aa2655c0342d0809d1'
silent! let g:plugs['vim-gitgutter'].commit = 'ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d'
silent! let g:plugs['vim-grepper'].commit = 'e9004ce564891412cfe433cfbb97295cccd06b39'
silent! let g:plugs['vim-one'].commit = 'f8bcef1968f01842d92abbcb098ec28ad3931ea5'
silent! let g:plugs['vim-polyglot'].commit = '6422a5a479905bf32abe7a322d1c0b0a75d4aa8c'
silent! let g:plugs['vim-snippets'].commit = '4552876fb40c3a0b0c3f563ed97419b03d3c61b8'
silent! let g:plugs['vim-startify'].commit = 'f2fc11844b234479d37bef37faa7ceb2aade788b'
silent! let g:plugs['vim-visual-multi'].commit = '61855432df721f01e5b64fec07bf7a9077ff32b5'
silent! let g:plugs['vista.vim'].commit = '27889ff58d4340167bb8dd4abbe9ff4a8869da8f'
silent! let g:plugs['zoomwintab.vim'].commit = '3b33368ed2ff6138d07f7ee148306cce7d7f6b7c'

PlugUpdate!

